trigger:
- master

pool:
  vmImage: 'windows-latest'   # hosted agent (easy)

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore AzDevOpsDemoGenerator/src/ADOGenerator/ADOGenerator.csproj
  displayName: Restore

- script: dotnet build AzDevOpsDemoGenerator/src/ADOGenerator/ADOGenerator.csproj --configuration $(buildConfiguration)
  displayName: Build

- script: dotnet publish AzDevOpsDemoGenerator/src/ADOGenerator/ADOGenerator.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: Publish

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
