trigger:
- master

pool:
  name: Default

steps:

- script: dir
  displayName: Show repository files

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore AzDevOpsDemoGenerator/src/ADOGenerator/ADOGenerator.csproj
  displayName: Restore dependencies

- script: dotnet build AzDevOpsDemoGenerator/src/ADOGenerator/ADOGenerator.csproj --configuration Release
  displayName: Build project